export default {
	SET_NAME:"SET_NAME",
	GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
	GET_LOCATION_INPUT: "GET_LOCATION_INPUT",
	GET_ADDRESS_PREDICTIONS : "GET_ADDRESS_PREDICTIONS",
	SET_LOCATION_INPUT : "SET_LOCATION_INPUT"
};
