export default {
	SET_NAME:"SET_NAME",
	GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
	GET_ADDRESS_PREDICTIONS : "GET_ADDRESS_PREDICTIONS",
	SET_LOCATION_INPUT : "SET_LOCATION_INPUT",
	REMOVE_PREDICTIONS : "REMOVE_PREDICTIONS",
	SET_FARE : "SET_FARE",
	BOOK_ROUTE: "BOOK_ROUTE"
};
